POST http://localhost:3000/login

{"email": "test@asd.com","password": "123"}

###

POST http://localhost:3000/status

[{"email": "test@asd.com" ,"password": "123"}, {"email": "paco@asd.com" ,"password": "123"}]

###

GET http://localhost:3000/usuarios