POST http://localhost:3000/login

{"email": "user@asd.com","password": "12345678"}

###

POST http://localhost:3000/login

{"email": "test@asd.com", "password": "12345678"}

###

GET http://localhost:3000/status

###

GET http://localhost:3000/users