POST http://localhost:3000/login

{ "email": "aaa@aaa.aaa", "password": "123456789" }

###

POST http://localhost:3000/login

{ "email": "m@kinis.com", "password": "12345789" }

###

POST http://localhost:3000/register

{ "nick": "Klaus", "userName": "Bescano", "lastUserName":"Soll", "email": "test@asd.com", "description":"Soy mugeriego", "password": "12345678", "dateBirth":"1991-11-11", "avatar":"sad", "role":"user", "dateJoined":"1991-11-11", "status":"1" }

###

POST http://localhost:3000/rankings

{ "idUser": "18" }

###

GET http://localhost:3000/status
W
###

GET http://localhost:3000/users

###

GET http://localhost:3000/rankings


